language: java
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "hem3r-github"
script:
  - ./gradlew --info sonarqube -Dsonar.projectName=zonky-marketplace-observer -Dsonar.projectKey=HEm3R_zonky-marketplace-observer
